### ISSUE TITLE
file tags input crashed when supplied with list

### ISSUE THREAD

**Issue by ksobon** [HydraShare/hydra-dynamo#1]
file tags input says that it requires a "An optional list of tags...", which made me think that I need to supply it a list like this: 

<code>{"a", "b", "c"}</code>

That unfortunately is not true. It crashed Dynamo when I tried giving it a list. I am going to have a look at it, we might want to add a list handling for this input or make the description clearer as to what input is expected.

**Comment by mostaphaRoudsari** [comment]
Thanks @ksobon . I think It should handle both cases similar to how Grasshopper component [does](https://github.com/HydraShare/hydra-grasshopper/blob/master/src/Hydra_ExportFile.py#L114-L131). Either a list of values or values separated by ',' or ';'.

**Comment by alfarok** [comment]
Thanks @ksobon, I need to go back and setup similar safety parameters for all the inputs to avoid crashing.  @mostaphaRoudsari I am just finishing up finals at school so things have been crazy but I plan on addressing a lot of cleanup/refinement over my winter break.

**Comment by mostaphaRoudsari** [comment]
Thanks @alfarok! No worries. Best of luck with your finals. :moon:

**Comment by ksobon** [comment]
Yeah dude, don't worry about it. Good luck!

**Comment by alfarok** [comment]
Should be able to handle any type of string with delimiter or list now.
