### ISSUE TITLE
Invalid File Path After Exporting

### ISSUE THREAD

**Issue by alfarok** [HydraShare/hydra-dynamo#10]
After writing the dyn file to the proper GitHub directory users get an error when trying to save via Dynamo because the last save location was a temp folder that is created during the export and deleted.  Should be an easy fix.

**Comment by michaldengusiak** [comment]
yes, this is really disturbing..  Did you have a chance to look at this... I started to use it and this is really amazing tool.

**Comment by alfarok** [comment]
@mdengusi the current version of hydra for Dynamo is outdated unfortunately.  I have a brand new version ready to be released, however it is built off of Dynamo v1.3 for numerous reason which should be released very soon.  This new version addresses a number of issues and includes a background preview capture.  Sorry for any inconvenience.

**Comment by alfarok** [comment]
@mdengusi I can push the latest version later today to github if you want which will allow you to build the dlls and use the latest package on a daily build of dynamo

**Comment by michaldengusiak** [comment]
Hi this could be great! I could have a go and test

**Comment by alfarok** [comment]
@mdengusi your interest has encouraged me to take some time and build in a few additional features/tests.  I should have the updated build up in the next couple of days.  The file path issue has been resolved though.  Here is a preview of what is to come...
![hydra_node](https://cloud.githubusercontent.com/assets/13341935/24687260/e18568ca-1986-11e7-80d3-2df0db9964ba.jpg)

**Comment by michaldengusiak** [comment]
Hi,

This look great...
Suggestion... currently we need to click on share in order to share it, however we could use player functionality maybe it would be possible to have alternative input from node so we can run in from player? What do you think?

I tired to modified target folder so we just specify folder in my final destination so script will solve user case... I could not make it to work any suggestion on that?
C:\Users\mdengusi\Documents\GitHub\Examples

**Comment by alfarok** [comment]
I'm not super familiar with the dynamo player yet but it could most likely be accommodated.  Pressing the UI button calls a method that does the actual work in the Hydra nodes creating the appropriate files.  I can look into it after I get the current build stabilized.

I pushed a new version of the node last night that you should be able pull down from Github and build in VS if you want to give that a test.  The last issue I am having is that the actually Hydra webpage doesn't seem to be updating with my new files.  This is most likely because I have made too many calls in testing and my access may have been restricted or there is a bug in my JSON because all the appropriate files appear to be in the correct location.  Maybe you could give this a test and see if you run into similar issues?

**Comment by alfarok** [comment]
It seems to be working now but feel free to test the new node for any issues.

**Comment by mdengusiak** [comment]
Hi, I just got you latest version and did a clean build but  I am a bit lost, there are so many nodes...I have no idea how to use it...


![image](https://cloud.githubusercontent.com/assets/14005893/24775319/3678dd38-1b14-11e7-8a79-6605ed100858.png)

**Comment by alfarok** [comment]
@mdengusi after building go inside the dynamo_package folder, where there should be another folder named Hydra, copy this folder into your package folder. (should be something like C:\Users\YourName\AppData\Roaming\Dynamo\Dynamo Core\1.2\packages)

**Comment by mdengusiak** [comment]
@alfarok 
Hi, thanks, this worked perfectly...
got it working and I managed to produce an example in the selected GitHub folder. Also, I could save dynamo file in the correct path. This is great. Congratulations.
I can see that image is only from script...are we planning to have also image from canvas or even Revit?

I was using Dynamo 1.2.1.3083 and Revit 2017.1

[Nametest.zip](https://github.com/HydraShare/hydra-dynamo/files/903987/Nametest.zip)

**Comment by alfarok** [comment]
Yes the background preview capture works for Dynamo v1.3 which was actually just released today.  I have commented out the 1.3 code in the latest build but will test it out tonight to see if there are any issues.  I believe there were some API changes that may need to be addressed.  Glad it is working and thanks for your help!  I am going to close this issue as it appears to be resolved with this commit 3242402c54477e0971402cd59506c68472cae19e
