### ISSUE TITLE
Background Preview Waiting for 1.4

### ISSUE THREAD

**Issue by alfarok** [HydraShare/hydra-dynamo#12]
Everything is in place to capture the background preview geometry image, but it was not added to Dynamo version 1.3.0 as expected so we have to wait for 1.4.0.  In the meantime this functionality will work on dailybuilds (other issues could occur down the line though which doesn't make this a good option).

[See this thread](https://github.com/DynamoDS/Dynamo/pull/7076#issuecomment-245113889)

**Comment by alfarok** [comment]
It may be worth looking into writing our own capture as we initially discussed because of the delay and we are still going to run into quality issue ([discussed here](https://github.com/HydraShare/hydra-dynamo/issues/2)) with the out-of-the-box capture tools on large definitions.

**Comment by schaggar16** [comment]
@alfarok i am very interested in the functionality of being able to capture the image of the background preview geometry image. Was very excited to see this functionality in 1.3 but alas wasn't to be. 
is it possible to setup a node in one of the current stable dynamo builds to do this?

**Comment by alfarok** [comment]
@schaggar16 There are 2 options if you want to capture the background preview before the 1.4.0 release.  If you have to use a stable build such as 1.3.0 you would have to write your own capture function.  Ian has already written this so you could just reference the existing logic and write a version that works in something like a zero touch/custom UI node.  The other option would be to use a a daily build of dynamo and un-comment the OnRequestSave3DImage method [here](https://github.com/HydraShare/hydra-dynamo/blob/master/src/HydraHelperFunctions/HydraHelpers.cs#L299) (but be aware the node isn't tested against new daily build implementations which may lead to unexpected crashes).

I have looked into the first option and while it is definitely possible I am not sure if it is worth putting something together that is inevitably going to be replaced in less than 6 months.  That being said I think we are going to run into image quality issues on really large graphs so writing a new screen capture that uses some type of bitmap processing to stitch images together would be beneficial.  I have't had the chance to sit down and dig into that yet but am hoping to soon.

Let me know if you have any other questions on the subject, but I hope this helps.

**Comment by schaggar16** [comment]
@alfarok thank you for the reply. While i do agree that the custom node would be abortive work, this is still a very useful function that i know i can put to use straight away. I do like the idea of having a node which can then be used to drive the further development - i guess just need a starting point. Would you be able post a link to Ian's work on this please? 
in all honesty i haven't really got to grips with putting together zero touch/custom UI nodes, how much work do you reckon it is to implement Ians work into a custom node? even if there are image quality issues, it gives a platform to develop from.

**Comment by alfarok** [comment]
@schaggar16 no problem, the link in the first post points to the pull request where you can look through the modified files.  Most of them are UI related but you just need the method that actually captures the geometry.  I think the most challenging part is going to be making sure the canvas for the bitmap capture is set exclusively as the background preview to ensure you are only copying that single window.  I am guessing the background preview is passed as a parameter somewhere in the method to accomplish this.

It may be a bit challenging for a first custom node project but I would check out this wiki [(Zero Touch Plugin Development)](https://github.com/DynamoDS/Dynamo/wiki/Zero-Touch-Plugin-Development) as a starting point

**Comment by alfarok** [comment]
Background preview available in Dynamo Core v2.0.  This feature has been implemented into the node in https://github.com/HydraShare/hydra-dynamo/pull/16
