### ISSUE TITLE
Hydra for Dynamo should be Core 2.0 compliant

### ISSUE THREAD

**Issue by alfarok** [HydraShare/hydra-dynamo#14]
The Hydra node for Dynamo needs to:
- Achieve parity with the Grasshopper component
- Achieve greater stability than previous implementations
- Capture background preview (finally possible in 2.0 without custom logic)

Early prototype:
![hydra2](https://user-images.githubusercontent.com/13341935/36064887-fdab987a-0e5f-11e8-835b-27df2562c7da.gif)

@mostaphaRoudsari I am curious what you think about this type of approach?

**Comment by mostaphaRoudsari** [comment]
Hi @alfarok, it looks legit. 💯
Now that you're going this far how hard is it to add it as a menu item? Does Dynamo give access to modify the menu items? It now looks like some of the functionalities of MetaHopper plugin for Grasshopper.

![screenshot 17](https://user-images.githubusercontent.com/2915573/36075047-944cc388-0f16-11e8-8d0a-61260250951f.png)

**Comment by alfarok** [comment]
@mostaphaRoudsari Yes we could do something similar using a view extension.  Check out [this](https://www.youtube.com/watch?v=qXHMFWbzC-0) project, it’s a view extension that instantiates a CEF browser executing three.js.

**Comment by mostaphaRoudsari** [comment]
@alfarok,  Yes! That's it. I think that would be the better solution. One main difference is that we don't end up with having an unnecessary component in canvas when the file is shared. To me that's a major advantage. Which one do you prefer?

**Comment by alfarok** [comment]
@mostaphaRoudsari I agree that the experience of using Hydra in a pop-out window could be more powerful and beneficial long term.  Ultimately it would be cool to push/pull directly from Dynamo/Grasshopper without having to use another Git client.  We could even enable internet access in CEF allowing users to browse the Hydra repo from within Dynamo.  This seems like a slightly larger project so I would prefer to initially use a node that establishes parity with the Grasshopper component.  I can avoid the issue of multiple nodes by iterating the current workspace and verifying another Hydra node is not present when the constructor is called.  We should talk more about the extension though because I think it is a great next step.

**Comment by alfarok** [comment]
Addressed in https://github.com/HydraShare/hydra-dynamo/pull/16
