### ISSUE TITLE
Dynamo Geometry Screenshot 

### ISSUE THREAD

**Issue by alfarok** [HydraShare/hydra-dynamo#8]
As previously mentioned there is no built in functionality for capturing a screenshot of the dynamo geometry, just the node graph view.  

@mjkkirschner
My approach was to try and use the RenderTargetBitmap class and render the geometry as a visual object as shown below

```
RenderTargetBitmap renderTargetBitmap = new RenderTargetBitmap(pixelWidth, pixelHeight, 96, 96, PixelFormats.Pbgra32);
renderTargetBitmap.Render(geometryView);
PngBitmapEncoder pngImage = new PngBitmapEncoder();
pngImage.Frames.Add(BitmapFrame.Create(renderTargetBitmap));
using (Stream fileStream = File.Create(screenshotPath))
    {
         pngImage.Save(fileStream);
    }
```

This works fine in the custom UI node for capturing the node view/graph but I can't seem to get the geometry despite trying many objects related to the 3D view.  Any ideas on things I could try or am I taking the wrong approach?

**Comment by ksobon** [comment]
Does this help? https://github.com/DynamoDS/Dynamo/pull/7076

**Comment by alfarok** [comment]
@ksobon I actually saw this on twitter last night!  I am going to work on implementing it ASAP.  Also thanks for the PR that was something that was way overdue and I've been wanted to get back into this project for a while.

**Comment by ksobon** [comment]
I basically re-made the whole thing from scratch because it was kinda hard to track down all of the things that needed to be renamed, removed etc. It was faster this way, but made the branch non-compatible. Sorry about that.

**Comment by alfarok** [comment]
No worries, since it was just a clone of the Dynamo samples originally it was inevitable

**Comment by alfarok** [comment]
@ksobon  screenshot of background preview implemented.  I am going to wait to push until the capture is merged in Dynamo.  [Check it out](http://hydrashare.github.io/hydra/viewer?owner=alfarok&fork=hydra&id=DynamoTest1&slide=1&scale=1&offset=0,0)

**Comment by ksobon** [comment]
Well done! Yeah its a good idea to wait with publishing but i think you can push to github. I doubt anyone except us ever builds from source. 😉

**Comment by alfarok** [comment]
valid point haha, just pushed

**Comment by alfarok** [comment]
@ksobon just realized the method I was originally using to do this was made virtual so it is going to crash dynamo.  I will get this fixed asap

**Comment by alfarok** [comment]
@ksobon @mostaphaRoudsari I rewrote this node using AST this week and will push the changes in the next few days (some of the old stuff still needs to be cleaned up).  I commented out the background 3d preview capture for now because the required method didn't make it into the 1.2 release and was supposed to be in 1.3 but based on the daily builds it looks like the next release will be 2.0?  I saw on twitter that Mostapha has some new Dynamo functionality coming soon so it may be somewhat useful

**Comment by mostaphaRoudsari** [comment]
@alfarok it will be quite helpful for me. I was to lazy to create the hydra examples manually for dynamo examples. :|

**Comment by alfarok** [comment]
@mostaphaRoudsari Sorry for the delay on this.  I tested everything today on a daily build and it seems to be working properly with canvas and background preview capture.  I am just waiting on the 1.3 release to push and update the package.

I was also wondering about directing more attention towards this project with the next release.  I think it could serve as a valuable resource in the Dynamo community for sharing files, but as we discussed Hydra has formed its own niche in regards to the type of content its currently hosting.  Do you have any opinions on how we might go about broadening the audience or creating a new branch?

**Comment by ksobon** [comment]
@alfarok @mostaphaRoudsari at what point does the HydraShare website becomes unusable because it was overloaded with shitty "test1", "test2" "testing" examples? I know that so far it was mostly Mostapha and Chris posting Ladybug samples, but its only a matter of time right? Do we want to curate the content? Or is it more about the temp storage space and ability to share quickly?

**Comment by alfarok** [comment]
@ksobon On the Dynamo side that was my fault haha.  I was using 1 test file and every time I ran it the sample was pushed to the top even though it was the same example.  I also apologize that it has taken so long to get the Dynamo version up to date because the background preview capture kept getting pushed back to later releases and I didn't want to write a custom capture when I knew it was in the works.

However, I do think those are all valid questions. I don't think Hydra was really promoted to a larger audience after the original hackathon which is why it became more of a tool for Ladybug and Honeybee examples.  I wouldn't want to disturb that environment a year and half later which is why I am curious what you guys think would be best.  Github has also recently restricted the max size of Github Pages which is going to be a problem in the near future as is.

**Comment by alfarok** [comment]
@ksobon what do you think about letting the current site live as in and we create a new site called something like graphshare.io (or whatever) powered by Hydra.  We could basically start fresh and map out how to categorize/validate files using the meta data we collect.  Maybe the ability to upvote/downvote files helps to remove blanks/garbage.  This is still pretty broad but I am really interesting in building on this project.

**Comment by ksobon** [comment]
Yeah that's a good idea. Something along the lines of 5 down-votes will remove the file from your server. I much more like that than, just letting people post garbage. Look what happened to Dynamo Package Manager. Not being able to take things down, and no validation basically created something that's unusable at this point.

**Comment by alfarok** [comment]
Okay awesome, I can setup a repo later today to start outlining this better.  Any ideas for a project name?  Also @mostaphaRoudsari how do you feel about this?  The current hydra page would remain intact and depending on the development/success of the new platform maybe a future merger would occur with a proper categorization for the current Hydra ecosystem you and Chris have built.

**Comment by mostaphaRoudsari** [comment]
Hi @alfarok and @ksobon, The reason I never reached out to a larger audience is the fact that I didn't have time to get the infrastructure for that to work. We need both voting, checking the number of downloads, checking the number of page visit, etc to be able to keep it clean if so many people are going to use it. Also we needed better searching and so on.

That's the reason that we kept it low profile and never really promoted it to get more example files. It gets a lot of daily visit every days and my caching process which runs on a google spreadsheet is already gets over the maximum number of hourly requests.

The idea of creating a fresh version for dynamo files sounds very good. Specially the fact that you can run Dynamo definitions on the web (with some trick that I don't know) opens up a new potential to check the examples live, assuming there will be a way to support the packages. If you found a good way to implement vote up and down it would be great to make it part of Hydra too.

**Comment by alfarok** [comment]
thanks @mostaphaRoudsari I will look into it a bit and get back to you guys ( @ksobon ) if I come up with a solution.  I am also going to close this issue though as it has been resolved in the 1.3 build as well as the incorporation of a number of enhancements.  I'll start a new thread in the future to further this discussion.  
![hydra_node](https://cloud.githubusercontent.com/assets/13341935/24687500/e375bdd2-1987-11e7-855b-709bf7966d24.jpg)

**Comment by alfarok** [comment]
@mostaphaRoudsari How often does the github page refresh?  I am just curious if there is an error in my json formatting or I am not being patient lol

**Comment by mostaphaRoudsari** [comment]
Hi @alfarok, probably you're not being patient. :) It's currently set to update every 10 minutes if I'm not mistaken.
